# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'job_offer',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('openings', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='RentACoderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'technology',
            },
        ),
        migrations.AddField(
            model_name='rentacoderuser',
            name='technologies',
            field=models.ManyToManyField(to='rentacoder_app.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='rentacoder_app.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacoder_app.RentACoderUser'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='coder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacoder_app.RentACoderUser'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacoder_app.Project'),
        ),
    ]
