# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacoder_app', '0002_project_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
