# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacoder_app', '0003_project_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, blank=True, upload_to='files'),
        ),
    ]
