# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacoder_app', '0004_project_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together=set([('project', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectscore',
            unique_together=set([('project', 'coder')]),
        ),
    ]
